### PR TITLE
Background image feature in progress...

### LINKED ISSUE #50: Feature: Increase the size of the image's handles when increasing the size of the image
If we increase the size of an image and then zoom out this it what we see for the handles : 

small_handles

And it is difficult to click on one of those handles as it is too small. That's why the size of those handles should be increased proportionally to the increase of the image's size.

### LINKED ISSUE #51: BUG: App is crashing after image deletion in some particular cases
Bug appears in [this commit](https://github.com/Onetchou/Seamly2D/commit/c5f2c9fe11492559684ece2eeea9bfa410beb693).

To create the bug:
* Launch Seamly
* Create a new pattern (ctrl-N → Enter), then add an image
* Add a second image on top of it
* Resize the second image to the minimum size possible using the top right handle
* Move this image to the center of the first image
* Then right click on this small image and click delete
* 2 seconds later the software crashes with the message "pure virtual method called"
* If the software is launched with the debugger it raises the message  "segmentation fault"

### LINKED ISSUE #53: Feature: Rotate the sizing handle cursors to match the rotation of the image.
When an image is rotated the "fixed" standard QT arrow cursors  are disorienting as to which direction to move the mouse to resize. The cursors should match the rotation of the image

### LINKED ISSUE #57: BUG:  casting warning generated from ImageItem
Since the base class QGraphicsItem does inherit from Q_OBJECT , it generates a casting warning where the inherited class - which also inherits from Q_OBJECT - can not cast to the base class. In order to fix this the  Q_INTERFACES macro must be used. 

image

Don't believe there are instances of casting ImageItem to QGraphicsItem, but this will keep the compiler happy. It should be noted that the base class also needs to use the Q_DECLARE_INTERFACE macro - which QGraphicsItem does.

### LINKED ISSUE #59: Feature: Allow resizing with center handles when aspect ratio is locked
Display in status message that the aspect ratio is locked.

### LINKED ISSUE #60: BUG: image properties dialog is not using pattern unit
When the pattern unit is set in mm, the dialog stays in cm

### LINKED ISSUE #61: Feature: Add an error popup if the image selected can not be loaded

### LINKED ISSUE #62: Feature: add unit svg to the repo
There: src\libs\vmisc\share\resources\icon\svg

### LINKED ISSUE #63: Feature: Delete image using del key when image is selected

### PR DESCRIPTION
**Pull request by Onetchou**
Fixes crash at image deletion. 
Fixes #51 

Add a confirmation popup at image deletion linked with the corresponding checkbox in the preferences menu.

Ts files updated.

### CODE REVIEW

**Comment by Onetchou** [comment]
Fixes #53

**Comment by Onetchou** [comment]
Fixes #57

**Comment by Onetchou** [comment]
Fixes #50

**Review by jim555-lab — APPROVED** [review]

**Comment by Onetchou** [comment]
Fixes #60

**Comment by Onetchou** [comment]
Fixes #59 
Fixes #61

**Comment by Onetchou** [comment]
Fixes #62

**Comment by Onetchou** [comment]
Fixes #63

**Pull request merged**
