### PR TITLE
Background image feature in progress

### LINKED ISSUE #39: Feature: Add a status message when resizing an image using the handles explaining the shift and ctrl shortcuts

### LINKED ISSUE #55: Feature: Display sizing info in the status bar
As a visual feedback, display the size, rotation, and units info in the status bar while an image is active.

### LINKED ISSUE #56: BUG: Can not access Images page in the Toolbox
Can only access the Import Image toolbutton from the Toolbox Toolbar or the Tools menu. 

image

The QToolbox's need to be put in a Grid layout so all the Page labels display.

image

### LINKED ISSUE #64: BUG: Image width and height status message disappears when the mouse leaves a handle

### PR DESCRIPTION
**Pull request by jim555-lab**
Fixes #56

### CODE REVIEW

**Comment by jim555-lab** [comment]
Fixes #39

**Comment by jim555-lab** [comment]
Fixes #55

**Comment by Onetchou** [comment]
Maybe delete the spaces between numbers and units:
image

And add a highly visible bold "Aspect ratio locked" in the status bar when the aspect ratio is locked.

**Comment by Onetchou** [comment]
The status message disappears when a handle is not hovered anymore, even if the mouse is over the image : issue #64

**Comment by Onetchou** [comment]
+ add position?

**Comment by Onetchou** [comment]
feat: Image status message tells image name, position and if aspect ratio is locked. 
image
Same for the handle status message:
image
image

fix: Image status message is updated when the image is moved and does not disappear when hovering a handle.
 
refactor: add a showImageStatusMessage function

**Comment by Onetchou** [comment]
Fixes #64

**Review by Onetchou — APPROVED** [review]

**Pull request closed without merging**
